server:
  context-path: /girl
spring:
  profiles:
    active: dev
  datasource:
    primary:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/dbgirl
      username: huhuiyang
      password: CaptainHhy@163.com
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 6
      minIdle: 6
      maxActive: 21
      maxWait: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: utf-8
    mode: HTML5
    #prefix: classpath:/templates/
    suffix: .html
global:
  constants:
    version: ${random.int[1000,10000]}